DELETE FROM wishlist_items;
DELETE FROM wishlists;
DELETE FROM reviews;
DELETE FROM order_status_history;
DELETE FROM shippings;
DELETE FROM payments;
DELETE FROM cart_items;
DELETE FROM carts;
DELETE FROM order_coupons;
DELETE FROM coupons;
DELETE FROM order_details;
DELETE FROM orders;
DELETE FROM product_category;
DELETE FROM products_images;
DELETE FROM product_images;
DELETE FROM products;
DELETE FROM categories;
DELETE FROM password_reset_tokens;
DELETE FROM email_verification_tokens;
DELETE FROM user_audit;
DELETE FROM role_permissions;
DELETE FROM permissions;
DELETE FROM addresses;
DELETE FROM users;
ALTER TABLE wishlist_items AUTO_INCREMENT = 1;
ALTER TABLE wishlists AUTO_INCREMENT = 1;
ALTER TABLE reviews AUTO_INCREMENT = 1;
ALTER TABLE order_status_history AUTO_INCREMENT = 1;
ALTER TABLE shippings AUTO_INCREMENT = 1;
ALTER TABLE payments AUTO_INCREMENT = 1;
ALTER TABLE cart_items AUTO_INCREMENT = 1;
ALTER TABLE carts AUTO_INCREMENT = 1;
ALTER TABLE order_coupons AUTO_INCREMENT = 1;
ALTER TABLE coupons AUTO_INCREMENT = 1;
ALTER TABLE order_details AUTO_INCREMENT = 1;
ALTER TABLE orders AUTO_INCREMENT = 1;
ALTER TABLE product_category AUTO_INCREMENT = 1;
ALTER TABLE products_images AUTO_INCREMENT = 1;
ALTER TABLE product_images AUTO_INCREMENT = 1;
ALTER TABLE products AUTO_INCREMENT = 1;
ALTER TABLE categories AUTO_INCREMENT = 1;
ALTER TABLE password_reset_tokens AUTO_INCREMENT = 1;
ALTER TABLE email_verification_tokens AUTO_INCREMENT = 1;
ALTER TABLE user_audit AUTO_INCREMENT = 1;
ALTER TABLE role_permissions AUTO_INCREMENT = 1;
ALTER TABLE permissions AUTO_INCREMENT = 1;
ALTER TABLE addresses AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;